### ISSUE TITLE
Add Dark Mode theme toggle

### ISSUE THREAD

**Issue by RashikaKarki** [MLH-Fellowship/pod-3.1.3-portfolio#2]
It will be great if we can add a toggle to switch between dark and light mode in the template. 

I am thinking of something along the line of this image, maybe around the top right corner. 

![image](https://user-images.githubusercontent.com/41114269/125605388-4a84ead7-44d1-4b75-8a9e-a1d7ca270586.png)

**Comment by dtemir** [comment]
That's sounds kinda challenging, but I would love to try this. _Let me know if anybody wants to collaborate on this_

**Comment by Inoxia25** [comment]
@dtemir I would also like to work on this!

**Comment by robzwolf** [comment]
Closed by #30
