### ISSUE TITLE
Add GitHub Stats

### ISSUE THREAD

**Issue by louisefindlay23** [MLH-Fellowship/pod-3.1.3-portfolio#29]
Add a user's GitHub stats using something like this [GitHub action](https://github.com/jstrieb/github-stats) that auto generates SVGs that could be displayed in the About or a separate section.

**Comment by Inoxia25** [comment]
Hey @louisefindlay23. Really like this feature! Would love to try it out, though have not worked with integrating github stats before

**Comment by louisefindlay23** [comment]
> Hey @louisefindlay23. Really like this feature! Would love to try it out, though have not worked with integrating github stats before 

Neither have I. Thought it would be cool. Basically from the Github Profile readmes. 

Happy to collaborate if you need any help. Will be afk until 3pm (GMT + 1) but let me know.

**Comment by Inoxia25** [comment]
@louisefindlay23 Hey I tried it out and made a pull request. Do tell if you would like to improve anything.
Also, added a most used languages card!
