### ISSUE TITLE
Add social media links

### ISSUE THREAD

**Issue by RashikaKarki** [MLH-Fellowship/pod-3.1.3-portfolio#3]
At the moment, people can see your awesome work but there's no way for them to get in touch with you and network!
We can add them in the footer with an icon but open to your creativity here, or maybe having multiple options and anyone using this template can pick one or the other.

**Comment by Green-Ranger11** [comment]
I would like to work on this. If anyone wants to collaborate please let me know

**Comment by hurstkatelyn** [comment]
@Green-Ranger11 I could try to help

**Comment by jagnani73** [comment]
I think @Green-Ranger11 @hurstkatelyn you should start on it then, no one else is working on it

**Comment by louisefindlay23** [comment]
In `_config.yml`, there's variables for `twitter_username` and `github_username` and in my PR, #13, I added `linkedin_username` so you can use that for the username for the links.
