### ISSUE TITLE
Change UI for project details

### ISSUE THREAD

**Issue by RashikaKarki** [MLH-Fellowship/pod-3.1.3-portfolio#4]
At the moment when you click on your project, it goes to the project detail page but from a UI perspective, it might look good if we can make the cards clickable where an overlay could pop up with all the information related to the project.
Or, perhaps we can also add an option to switch between these options.

**Comment by prakharrathi25** [comment]
Hi, I would like to work on this issue. I have discussed it with the pod. Feel free to reach out if someone wants to collaborate.

**Comment by louisefindlay23** [comment]
Happy to help, @prakharrathi25 as discussed in Discord PMs

**Comment by louisefindlay23** [comment]
Hope our 1 on 1 helped, @prakharrathi25. Let me know if you need any more help tomorrow.

**Comment by prakharrathi25** [comment]
> Hope our 1 on 1 helped, @prakharrathi25. Let me know if you need any more help tomorrow.

It definitely did. I am through with the card fixes. Just looking at how to connect it to the JS so that the clicking feature works.

**Comment by louisefindlay23** [comment]
Awesome work, @prakharrathi25. Hope the links to JS articles I gave you help.

**Comment by Inoxia25** [comment]
@prakharrathi25 great work with the cards! I was wondering, maybe if we could add a link to the github repo and the deployed version to the project card, would be better. what say?

**Comment by prakharrathi25** [comment]
> @prakharrathi25 great work with the cards! I was wondering, maybe if we could add a link to the github repo and the deployed version to the project card, would be better. what say?

That's a really cool idea. We can definitely do that! I will create an issue for it. Thanks!
