### ISSUE TITLE
Add dropdown menu to navigation bar for smaller screens

### ISSUE THREAD

**Issue by ksaisudha24** [MLH-Fellowship/pod-3.1.3-portfolio#43]
Navigation bar works well for wide screens. For smaller screens, a dropdown menu to the top right corner would look good.

**Comment by Inoxia25** [comment]
working on this one!

**Comment by ksaisudha24** [comment]
@Inoxia25 I have already worked on the issue. I am going to make a PR now. I was waiting for permission to assign the issue to myself.

**Comment by Inoxia25** [comment]
@ksaisudha24 oh okay, didn't know you were already working on it

**Comment by ksaisudha24** [comment]
@Inoxia25 Sorry for not communicating it.
