### ISSUE TITLE
Pick cool colors for Dark Mode

### ISSUE THREAD

**Issue by dtemir** [MLH-Fellowship/pod-3.1.3-portfolio#44]
Right now, the dark mode is _ugly_, not gonna lie :smile: 
![Website in Dark Mode](https://user-images.githubusercontent.com/62047062/126495908-4c77c9fc-54d6-4d79-8ebb-fcf749d8f5c5.png)
We need to pick new colors for the general color scheme. @jagnani73 suggested https://coolors.co/ to get a new palette.

So if somebody is interested in design and color picking, feel free to dive in `main.scss` and update those colors with new ideas! **You can also send-in your version to discord for our support :superhero:**

**Comment by jagnani73** [comment]
Ill take up this issue!
