### ISSUE TITLE
Add a project details overlay card toggle feature

### ISSUE THREAD

**Issue by prakharrathi25** [MLH-Fellowship/pod-3.1.3-portfolio#46]
The project details section have a clickable card overlay which was created from issue #4 but now we need to add a toggle to it so that people can decide which projects need to have a popup and which ones don't.

**Comment by anandrajaram21** [comment]
I think a better implementation would be to have the overlay show up by default, and the user can click on a button in the overlay to take them to the github repo, or maybe another page on the portfolio website, which shows more details about the project.

**Comment by prakharrathi25** [comment]
That's exactly what I added through pull request #36. I want to extend that by making this feature optional based on whether the user wants the overlay or not.

**Comment by anandrajaram21** [comment]
Oh gosh, I'm sorry, I didn't notice that 😅. IMO, having it as suggested in pull request #36 would be the best way forward. I also think that most users would want the overlay by default, as its a much cleaner experience, and adding a "toggle" or "switch" of some sort would not have much of a benefit.

**Comment by prakharrathi25** [comment]
> Oh gosh, I'm sorry, I didn't notice that 😅. IMO, having it as suggested in pull request #36 would be the best way forward. I also think that most users would want the overlay by default, as its a much cleaner experience, and adding a "toggle" or "switch" of some sort would not have much of a benefit.

Yeah, I mentioned it my PR but even I was thinking the same thing. Having a default overlay is nicer but the original poster had mentioned it in the issue so I thought about working on it. I will find something else to work on. Thanks for the input!

**Comment by anandrajaram21** [comment]
Absolutely, I'm happy to help :)
