### ISSUE TITLE
Add a "scroll to top" button in the page

### ISSUE THREAD

**Issue by anandrajaram21** [MLH-Fellowship/pod-3.1.3-portfolio#47]
As the links in the navbar take you to different sections of the page, you might often feel the need to scroll to the top of the page. Adding a "scroll to top" button on the page would help users a lot, as the portfolio website is getting pretty long now.

**Comment by prakharrathi25** [comment]
I can work on this if someone isn't already. Good suggestion!

**Comment by anandrajaram21** [comment]
Yeah sure, go for it!

**Comment by prakharrathi25** [comment]
@Green-Ranger11 @hurstkatelyn are you creating a footer page for the social media links for issue #3 ? I might need a footer page for this as well. Wanted to see the structure if you're making a PR or maybe we could all work together on this.
