### ISSUE TITLE
Improving Dark Mode Toggle

### ISSUE THREAD

**Issue by louisefindlay23** [MLH-Fellowship/pod-3.1.3-portfolio#48]
Improve the current dark mode toggle. Currently, the toggle is at the left hand side with no space between it and the edge of the browser. There's also large text that's says enable Dark Mode.

- The toggle could be moved to the the top left similar to the navigation bar 

- The toggle switch could be modified to a sun and moon icon similar to this [article](https://dev.to/shadowscientist/making-a-dark-mode-switch-lightly-249j) - there's a Github repo and Codepen inside

**Comment by louisefindlay23** [comment]
@dtemir, would you be interested in working on this since you helped make the dark mode?

**Comment by dtemir** [comment]
@louisefindlay23 certainly!

**Comment by prakharrathi25** [comment]
@louisefindlay23 I would also love to join this one since we discussed this in our one-on-one. @dtemir If there's already a lot of progress here, then I will find another issue to work on.
