### ISSUE TITLE
Add Contact section

### ISSUE THREAD

**Issue by RashikaKarki** [MLH-Fellowship/pod-3.1.3-portfolio#5]
Generally, on a portfolio website, we have the option to contact the person directly using the website form. 
So, it will be great if we can add that section and perhaps link the form response to the email.

![image](https://user-images.githubusercontent.com/41114269/125609743-d06e54dc-d916-4153-bbc1-73eda7faf68f.png)

It can be something along the line of this.

**Comment by anandrajaram21** [comment]
I would love to work on this :+1:

**Comment by robzwolf** [comment]
Closed by #22
