### ISSUE TITLE
Add bio section

### ISSUE THREAD

**Issue by RashikaKarki** [MLH-Fellowship/pod-3.1.3-portfolio#6]
It would be great to have a bio section in the portfolio, where you all can talk more about who you are, and your programming story.

**Comment by MsMore** [comment]
I would like to work on it, as discussed with the pod

**Comment by MsRiddhi** [comment]
## Why this PR
Added a About me/Bio section in the existing index page, right below the profile section.
 
## Files added
1. about.html
2. about.scss
3. about.yml

![image](https://user-images.githubusercontent.com/60326931/126314958-2cc0940a-66eb-467f-8b5e-8eb5d332af5d.png)


It is responsive to smaller viewports as well. 
- The section is divided into two sub-sections; the `info` and the `bio` which are two separate div `child` inside one `about-section` div
- The responsiveness is defined in `about.scss` , using grid they have been stacked side-by-side and one top of another according to the screen size.

## Issue resolved
Issue #6

**Comment by robzwolf** [comment]
Closed by #11.

@MsMore You generally don't need to include the Pull Request contents on the Issue. Just linking to the Issue in the PR will automatically add a link to the PR on the Issue! :)
