### ISSUE TITLE
Add github and deploy links for projects in the overlay card

### ISSUE THREAD

**Issue by prakharrathi25** [MLH-Fellowship/pod-3.1.3-portfolio#61]
The overlay cards as created in issue #4 add a quick summary of the projects. It would be really nice if they could also have Github and Final Project links.

**Comment by prakharrathi25** [comment]
@robzwolf I am not able to assign myself to this issue. Could someone help out with that? @louisefindlay23 I think you faced the same issue. How did you fix it?

**Comment by Inoxia25** [comment]
@prakharrathi25 would love to work on this one. If you have already worked on it, then would work on another issue :grimacing:

**Comment by louisefindlay23** [comment]
@prakharrathi25, I haven't been able to fix it yet. Waiting for @robzwolf.

**Comment by prakharrathi25** [comment]
> @prakharrathi25 would love to work on this one. If you have already worked on it, then would work on another issue 😬

Sure, I will message you on discord and we can discuss.
