### ISSUE TITLE
Projects Cards have different width

### ISSUE THREAD

**Issue by Primata** [MLH-Fellowship/pod-3.1.3-portfolio#71]
I'm trying to look into the code and devTools, but I'm unable to diff between two similar elements in it. Both elements are identically created by projects.html for each project.md file.
![image](https://user-images.githubusercontent.com/6299375/126724892-17493a49-f5ad-48fc-8389-642c76cba968.png)

![image](https://user-images.githubusercontent.com/6299375/126724881-3ae6cfae-6907-4b32-9ca0-598152c05ccb.png)

Is anyone aware of some tool? I have looked for CS Diff but it seems like it's a broken extension.
People of issue #4 I'd like your help

**Comment by anandrajaram21** [comment]
I think I might be partly responsible for this issue. Let me take a look at this.

**Comment by jagnani73** [comment]
I have fixed it!
@anandrajaram21 Sorry; didn't know you were working on it!
